---
title: "Eliminating Racial Bias Relating to Violent Crimes in U.S. Communities using a Predictive Machine Learning Model"
author: "input our names here"
format: pdf
editor: visual
---

# Reading Libraries and Dataset

```{r}
#loads packages
packages <- c(
    # Old packages
    "ISLR2",
    "dplyr",
    "tidyr",
    "readr",
    "purrr",
    "glmnet",
    "caret",
    "repr",
    # NEW
    "torch",
    "mlbench",
    "Stat2Data",
    "ggformula",
    "mosaic"
)

# renv::install(packages)
sapply(packages, require, character.only=TRUE)

Data <- read.csv("https://raw.githubusercontent.com/snehaprem03/StatProject/main/communities.data")
```

\-

# Data Tidying and Manipulation


```{r}
#eliminates country and community which we said was not useful since they had lots of ?
df <- Data %>%
  dplyr::select(-country, -community)
```

```{r}
df %>% 
keep(is.numeric) %>% 
gather() %>% 
ggplot(aes(y=value)) +
geom_boxplot() +
facet_wrap(~ key,scales="free")
```

\-

# Variable Creation, Selection, and Manipulation

```{r}

```

\-

# Introductory Plots

```{r}
gf_point(ViolentCrimesPerPop ~ medIncome, data = df)
```

```{r}
gf_point(ViolentCrimesPerPop ~ PctTeen2Par, data = df)
```


```{r}
df %>%
  group_by(state) %>%
gf_point(state ~ medIncome, data = df)
```


\-

# Exploratory Data Analysis

```{r}
model <- lm(ViolentCrimesPerPop ~ ., data = df)
summary(model)
plot(model)
plotModel(model)
```

\-

